            <h2>Latest emails</h2>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Recipient</th>
                        <th>Sender</th>
                        <th>Time</th>
                        <th>Status</th>
                        <th>Content</th>
                        <th>Spam level</th>
                    </tr>
                </thead>
                <tbody>
<?php foreach ($this->latest as $mail): ?>
                    <tr>
                        <td><?php echo $mail['recipient']; ?></td>
                        <td><?php echo mb_substr($mail['sender'], 0, 50); ?></td>
                        <td><?php echo $mail['time_iso']; ?></td>
                        <td><?php echo $this->deliveryStatus($mail['delivery_status']); ?></td>
                        <td><?php echo $this->messageType($mail['content']); ?></td>
                        <td><?php echo $mail['spam_level']; ?></td>
                    </tr>
<?php endforeach; ?>
                </tbody>
            </table>

<?php
    echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'paginator.phtml'
    );
?>