<?php
$this->inlineScript()->appendScript("
$('.tt').each(function() {
    $(this).tooltip( { delay: { show: 50, hide: 2 }, trigger: 'hover' } );
});
");
?>

            <h1>Hosted domains</h1>

            <table class="table table-big table-striped" id="domainList">
                <thead>
                    <tr>
                        <th style="width:30%">Domain</th>
                        <th class="center">Emails</th>
                        <th class="center">Aliases</th>
                        <th class="center">Active</th>
                        <th class="center">Backup</th>
                        <th style="width:120px">Options</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="#">ccentar.com</a></td>
                        <td>7</td>
                        <td>2</td>
                        <td>Yes</td>
                        <td>No</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-mini tt" title="Edit domain" href="#">
                                    <i class="icon icon-pencil">Edit</i>
                                </a>
                                <a class="btn btn-mini tt" title="Administrators" href="#">
                                    <i class="icon icon-user">Administrators</i>
                                </a>
                                <a class="btn btn-mini tt" tabindex="1" title="Logs" href="#">
                                    <i class="icon icon-align-justify">Logs</i>
                                </a>
                                <span  class="btn btn-mini tt" title="Delete">
                                    <i class="icon icon-trash">Delete</i>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td><a href="#">grafiknet.hr</a></td>
                        <td>7</td>
                        <td>2</td>
                        <td>Yes</td>
                        <td>No</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-mini tt" title="Edit domain" href="#">
                                    <i class="icon icon-pencil">Edit</i>
                                </a>
                                <a class="btn btn-mini tt" title="Administrators" href="#">
                                    <i class="icon icon-user">Administrators</i>
                                </a>
                                <a class="btn btn-mini tt" tabindex="1" title="Logs" href="#">
                                    <i class="icon icon-align-justify">Logs</i>
                                </a>
                                <span  class="btn btn-mini tt" title="Delete">
                                    <i class="icon icon-trash">Delete</i>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td><a href="#">grafiknet.hr</a></td>
                        <td>7</td>
                        <td>2</td>
                        <td>Yes</td>
                        <td>No</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-mini tt" title="Edit domain" href="#">
                                    <i class="icon icon-pencil">Edit</i>
                                </a>
                                <a class="btn btn-mini tt" title="Administrators" href="#">
                                    <i class="icon icon-user">Administrators</i>
                                </a>
                                <a class="btn btn-mini tt" tabindex="1" title="Logs" href="#">
                                    <i class="icon icon-align-justify">Logs</i>
                                </a>
                                <span  class="btn btn-mini tt" title="Delete">
                                    <i class="icon icon-trash">Delete</i>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td><a href="#">grafiknet.hr</a></td>
                        <td>7</td>
                        <td>2</td>
                        <td>Yes</td>
                        <td>No</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-mini tt" title="Edit domain" href="#">
                                    <i class="icon icon-pencil">Edit</i>
                                </a>
                                <a class="btn btn-mini tt" title="Administrators" href="#">
                                    <i class="icon icon-user">Administrators</i>
                                </a>
                                <a class="btn btn-mini tt" tabindex="1" title="Logs" href="#">
                                    <i class="icon icon-align-justify">Logs</i>
                                </a>
                                <span  class="btn btn-mini tt" title="Delete">
                                    <i class="icon icon-trash">Delete</i>
                                </span>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
